name: build multi
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - multi/**
jobs:
  push:
    name: "yolks:multi"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./multi
          file: ./multi/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/lorenzo0111/yolks:multi
          cache-from: type=gha
          cache-to: type=gha,mode=max
